### ISSUE TITLE
Crashing Geode on loadup (Android) 

### ISSUE THREAD

**Issue by ProblemReporter745** [acaruso-xx/pride-geode#1]
When starting up geode after installing the mod, it just crashed. 
I don't know anything about coding but I hope the file that Geode said to share helps. 
[Crash_2024-06-12_13.47.45.dmp](https://github.com/user-attachments/files/15808962/Crash_2024-06-12_13.47.45.dmp)

**Comment by ProblemReporter745** [comment]
I hope that changing the file type to the dmp still made it openable

**Comment by ProblemReporter745** [comment]
oops

**Comment by lightyisreal** [comment]
Still a thing
