### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by pauliesnug** [acaruso-xx/pride-geode#2]

**Comment by acaruso-xx** [comment]
Added in https://github.com/acaruso-xx/pride-geode/commit/eab7e9daeca6d34772e81e6665b8ad843e46dda7.

**Comment by pauliesnug** [comment]
> Added in [eab7e9d](https://github.com/acaruso-xx/pride-geode/commit/eab7e9daeca6d34772e81e6665b8ad843e46dda7).

Thank you so much!
