### ISSUE TITLE
Wave issues

### ISSUE THREAD

**Issue by Raptoxa** [acaruso-xx/pride-geode#4]
the trail disappears after you become a wave and only reappears when you re-open the level.

**Comment by StatusZer0** [comment]
I've been experiencing this, too. Really hope it gets fixed

**Comment by acaruso-xx** [comment]
TheBearodactyl/gay-wave-trail#6

**Comment by TheBearodactyl** [comment]
@StatusZer0 @Raptoxa  if you have Gay Wave Trail installed, there's a setting for the mod to disable regular trail. disable that option and you're problem is solved
