### ISSUE TITLE
The mod dosent do anythting

### ISSUE THREAD

**Issue by om3ga6400** [acaruso-xx/pride-geode#7]
when i have the mod installed none of the trails change

**Comment by OM3GA6400** [comment]
@acaruso-xx

**Comment by TheBearodactyl** [comment]
> when i have the mod installed none of the trails change

@OM3GA6400 what other mods do you have installed

**Comment by OM3GA6400** [comment]
qolmod

**Comment by TheBearodactyl** [comment]
> qolmod

ask @TheSillyDoggo to add pride trails compatibility

**Comment by OM3GA6400** [comment]
> > qolmod
> 
> ask @TheSillyDoggo to add pride trails compatibility

just uninstalled qolmod and the mod still dose nothing

**Comment by OM3GA6400** [comment]
![Screenshot_20240819_082420_Geode.jpg](https://github.com/user-attachments/assets/c42cc666-9160-40be-86e9-7d31017cf8d2)

**Comment by om3ga6400** [comment]
@TheBearodactyl

**Comment by TheBearodactyl** [comment]
> ![Screenshot_20240819_082420_Geode.jpg](https://private-user-images.githubusercontent.com/98067930/359099041-c42cc666-9160-40be-86e9-7d31017cf8d2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDAzMzgsIm5iZiI6MTcyNjcwMDAzOCwicGF0aCI6Ii85ODA2NzkzMC8zNTkwOTkwNDEtYzQyY2M2NjYtOTE2MC00MGJlLTg2ZTktN2QzMTAxN2NmOGQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDIyNTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ODVmZWM3ZDU5MGIzOTg1MjM1NzEwNGZiYzA0N2Y4NDY1NzlkYjdkOGZkYTJjYjg1MjUwM2FlZjRlNDY3MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kv34YgfXScEUkebuIETF9oCWOTH5NDuxoQfUTLAJqdw)

did you try choosing the rainbow trail that's literally right there

**Comment by om3ga6400** [comment]
yeah its just the normal one

**Comment by TheBearodactyl** [comment]
> yeah its just the normal one

try pressing it

**Comment by TheBearodactyl** [comment]
@om3ga6400 
https://github.com/user-attachments/assets/d606f801-f995-4148-be40-4526fefb1ffc

**Comment by om3ga6400** [comment]
oh so thats what i've been supposed to do, ty

**Comment by TheBearodactyl** [comment]
np
